# Generated by Django 5.1.1 on 2024-10-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skystarz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='new_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skystarz.moon'),
        ),
    ]
